In [9]:
import pandas as pd

In [10]:
# 1) df_tips içindeki Payment ID column'unun son 3 rakamını çekin. Bu işlemi 3 farklı yolla da yapmaya çalışın.

df_tips = pd.DataFrame(pd.read_csv("../datas/tips.csv"))

df_tips["Payment ID"].tail(3)
df_tips["Payment ID"].iloc[241:244]
df_tips["Payment ID"].loc[241:244]

241    Sat3880
242      Sat17
243    Thur672
Name: Payment ID, dtype: object

In [11]:
# 2) df_tips içindeki Payer Name sütununda isim ve soy isim bilgileri bulunuyor. 
# O sütundan sadece isim bilgileri çekin ve 'JustName' adında yeni bir column oluşturun. 

# .str.split() → Boşluk karakterine göre böler, örneğin "Ahmet Yılmaz" → ["Ahmet", "Yılmaz"]
# .str[0] → Bu listenin ilk elemanını, yani ismi alır: "Ahmet"
# Pandas'ta .str, metin (string) verileri üzerinde çalışmak için özel bir erişim noktasıdır. 
# Liste gibi değil, DataFrame'in bir sütununda tüm hücrelere aynı anda metin işlemi uygulamak istediğinde .str kullanılır.

df_tips["JustName"] = df_tips["Payer Name"].str.split().str[0]
df_tips

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,JustName
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,Christy
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,Douglas
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,Travis
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,Nathaniel
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,Tonya
...,...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657,Michael
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766,Monica
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880,Keith
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17,Dennis
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672,Michelle

In [12]:
# 3) 2.Soruda yeni oluşturduğunuz 'JustName' sütunundaki verilerin her birinden kaç tane olduğuna uygun methodu kullanarak bakın.

df_tips["JustName"].value_counts()

JustName
Jason          9
Michael        7
James          6
David          6
Christopher    5
              ..
Shawna         1
Louis          1
Chris          1
Mark           1
Michelle       1
Name: count, Length: 153, dtype: int64

In [13]:
# 4) 3.Soruda gördüğünüz gibi JustName sütununda 'Jason' isminden 9 tane, 'Michael' isminden 7 tane , 'James' isminden 6 tane bulunuyor. 
# Peki bunların hepsi gerçekten farklı kişiler mi ? Hemen 'Payer Name' sütunundaki verilerin adetlerini de saydırtarak bir kıyaslama yapın. 
# 'JustName' sütununu kullanmanın faydasız ve yanıltıcı olabileceğini görün ardından oluşturduğumuz 'JustName' sütununu kalıcı olarak drop edin

print(df_tips["Payer Name"].value_counts())
df_tips.drop("JustName", axis=1, inplace=True)

Payer Name
Christy Cunningham    1
Todd Patterson        1
Madison Wilson        1
Ryan Gonzales         1
Laura Robles          1
                     ..
Shawna Cook           1
Derek Thomas          1
Donald Williams       1
Roger Taylor          1
Michelle Hardin       1
Name: count, Length: 244, dtype: int64

In [14]:
# 5) Erkeklerin ve kadınların davranış patternlerini ayrı ayrı inceleyip yorumda 
# bulunabilmek için 'df_male' ve 'df_female' adında 2 dataframe oluşturun. 
# Birinde sadece 157 erkek verisi, diğerinde sadece 87 kadın verisi bulunsun.

df_male = df_tips[df_tips["sex"] == "Male"]
df_female = df_tips[df_tips["sex"] == "Female"]

In [15]:
# 6) Ardından bu 'df_male' ile 'df_female' 'in ödedikleri bahşişler toplamını bulup karşılaştırın.

total_bill_male   = df_male["total_bill"].sum()
total_bill_female = df_female["total_bill"].sum()

f"Erkekeler: {total_bill_male} - Kadınlar: {total_bill_female}"

'Erkekeler: 3256.8199999999997 - Kadınlar: 1570.9499999999996'

In [16]:
# 7) 6.Soruda erkeklerin ve kadınların ödedikleri bahşişler toplamına bakıldığında Erkeklerin kadınlara kıyasla toplamda daha çok bahşiş ödediğini görüyoruz. 
# Fakat biz biliyoruz ki bizim verimizde 157 Erkek, 87 kadın verisi vardı.
# Dolayısıyla Erkek sayısı daha fazla olduğu için toplam ödeyecekleri bahşiş miktarlarında da daha fazla çıkması oldukça normal bir durum. 
# Bu yüzden daha mantıklı bir çıkarım için bu sefer df_male ile df_female'in bahşiş ORTALAMALARIN'a bakıp kıyaslayın, 
# aralarında anlamlı ve ciddi bir fark var mı ?

male_bill_mean = df_male["total_bill"].mean()
female_bill_mean = df_female["total_bill"].mean()

f"Erkekeler: {male_bill_mean} - Kadınlar: {female_bill_mean}"

'Erkekeler: 20.744076433121016 - Kadınlar: 18.056896551724133'

In [17]:
# 8) Oluşturmuş olduğunuz df_male ile çalışarak elimizdeki verideki erkeklerin yüzde kaçının sigara içtiğini bulun. 
# Aynı şekilde elimizdeki kadınların yüzde kaçının sigara içtiğini de bulun. Aralarında anlamlı bir fark mı yorumlayın.

male_radio_smoker   = (df_male[df_male["smoker"] == "Yes"].shape[0] / df_male.shape[0]) * 100
female_radio_smoker = (df_female[df_female["smoker"] == "Yes"].shape[0] / df_female.shape[0]) * 100

f"Erkekeler: {male_radio_smoker} - Kadınlar: {female_radio_smoker}"

'Erkekeler: 38.21656050955414 - Kadınlar: 37.93103448275862'

In [18]:
# 9) Erkeklerin zaman olarak dinnerda mı yoksa lunch'da mı daha fazla yemek yediğini yüzdesel olarak bulun. Aynı işlemi kadınlar için de yapın. 
# Yüzdesel olarak erkeklerin ve kadınların yemek yeme vakitleri arasında anlamlı bir fark var mı yok mu yorumlayın.

male_lunch  = df_male[df_male["time"] == "Lunch"].shape[0]
male_dinner = df_male[df_male["time"] == "Dinner"].shape[0]

female_lunch  = df_female[df_female["time"] == "Lunch"].shape[0]
female_lunch = df_female[df_female["time"] == "Dinner"].shape[0]

f"Erkekler --> lunch: {male_lunch} - dinner: {male_dinner} / Kadınlar --> lunch: {female_lunch} - dinner: {female_lunch}"

'Erkekler --> lunch: 33 - dinner: 124 / Kadınlar --> lunch: 52 - dinner: 52'

In [19]:
# 10) CC Number sütununu kalıcı olarak drop edin. Ardından df'in içindeki sütunların birbirleriyle olan ilişkilerini inceleyin ve çıkan sonuçlar hakkında yorumlarınızı belirtin.

df_tips.drop(labels="CC Number", axis=1, inplace=True)

In [20]:
df_tips

# Erkeklerin  %26 sı yemeğini öğle yerken, %74 i akşam yiyor
# Kadınlarda ise bu oran %50 ye %50
# Erkeklerin sigara içme oranı kadınlara göre daha yüksek
# Erkekler kişi başı oran olarak kadınlara göre daha fazla bahşiş veriyor
# Ama genel olarak bu oranlar arasında çok ciddi farklar yok birbirine yakın seyrediyorlar

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,Sun2251
...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,Thur672